#server:
#  port: 8761
#eureka:
#  server:
#    enable-self-preservation: false  #关闭自我保护机制
#    eviction-interval-timer-in-ms: 60000 #设置清理间隔（单位：毫秒 默认是60*1000）
#  instance:
#    hostname: localhost
#
#  client:
#      registerWithEureka: false #不把自己作为一个客户端注册到自己身上
#      fetchRegistry: false  #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注册了）
#      serviceUrl: #微服务要注册到的地址.
#        #http://localhost:3000/eureka
#        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
